version: "3.8"

services:
  db:
    container_name: eleicoes-db
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=eleicoes_bd
      - POSTGRES_USER=scott
      - POSTGRES_PASSWORD=tiger
    volumes:
      - postgres-eleicoes-db-data:/data

volumes:
  postgres-eleicoes-db-data:
